In [ ]:
print("hello")

hello


In [ ]:
import numpy
# import numpy as np
# from numpy import arange
# from numpy import *
# n = numpy.arange(11)
# print(type(n))
# print(n)
# print(n[0])


# example
# n = numpy.arange(12)
# d = n.reshape(3,4) # 3 -> rows or 4 -> cols
# print(type(d))
# print(d)

#example 2d
# n = numpy.arange(12).reshape(4,3)
# print(n)


# example 3d
# n = numpy.arange(24).reshape(1,6,4) # 3-> rows or 4 -> cols
# print(n)


# example split # 2,5,8,11 -> print
# n = numpy.arange(12).reshape(4,3)
# print(n)
# print(n[0:4:,2]) # first row or second cols
# print(n[0:4,2:4]) # first row or second cols
# print(n[:,-1])

#example split # 4,7 -> print
n = numpy.arange(12).reshape(4,3)
print(n)
print(n[1:3,1:2])


[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
[[4]
 [7]]


**creating array from list**
1. 1d
2. 2d

**list vs numpy array**
1. Example of multi with list and array
2. time comparsion
3. zeros (3,4)
4. ones (2,3)
5. full ((2,2),7)
6. random (2,3)
7. arange (0,10,2)

**Vector,matrix,tensor**
1. vector (1d)
2. matrix (2d)
3. tensor (3d)

**Array properties**
1. shape
2. dimension
3. size
4. dtype

**Array Reshaping**
1. reshape()
2. flatten() -> create copy
3. ravel() -> return original
4. transpose

**Numpy Array operations**
1. slicing for 1d,2d,3d


**Looping with numpy**
1. while loop
2. for loop

**Sorting**
1. sort() for 1d
2. sort() for 2d ,use axis=0-> cols,axis=1-> rows


**Filter**
1. array[Expression]
2. array[array>2] || filter with mask

**Fancy indexing vs np.where()**
1. array(list)
2. array([0,1,2])

3. np.where(expression)
4. np.where(array>2)