In [ ]:
print("hello")

hello


In [ ]:
import numpy
# import numpy as np
# from numpy import arange
# from numpy import *
# n = numpy.arange(11)
# print(type(n))
# print(n)
# print(n[0])


# example
# n = numpy.arange(12)
# d = n.reshape(3,4) # 3 -> rows or 4 -> cols
# print(type(d))
# print(d)

#example 2d
# n = numpy.arange(12).reshape(4,3)
# print(n)


# example 3d
# n = numpy.arange(24).reshape(1,6,4) # 3-> rows or 4 -> cols
# print(n)


# example split # 2,5,8,11 -> print
# n = numpy.arange(12).reshape(4,3)
# print(n)
# print(n[0:4:,2]) # first row or second cols
# print(n[0:4,2:4]) # first row or second cols
# print(n[:,-1])

#example split # 4,7 -> print
n = numpy.arange(12).reshape(4,3)
print(n)
print(n[1:3,1:2])


[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
[[4]
 [7]]


**creating array from list**
1. 1d
2. 2d

In [ ]:
# import numpy as np
# # list 1d
# l = [1,2,3]
# print(l)

# # array 1d
# arr = np.array(l)
# print(arr)

# 2d example

import numpy as np
# 2d list
l = [[1,2,3],[4,5,6]]
print(l)
print(l[0]) # [1,2,3] -> 1row
print(l[0][0]) # [1,2,3] -> 1row -> first element -> 1

# question list value 4 -> 100
l[1][0] = 100
print(l[1])

# 2d array
arr = np.array([[1,2,3],[4,5,6]])
print(arr)
print(arr[0]) # [1,2,3] -> 1 row
print(arr[0][0]) # [1,2,3] -> 1row -> first element -> 1

# question array value 4 -> 100
arr[1][0] = 100
print(arr[1])

[[1, 2, 3], [4, 5, 6]]
[[1 2 3]
 [4 5 6]]


**list vs numpy array**
1. Example of multi with list and array
2. time comparsion
3. zeros (3,4)
4. ones (2,3)
5. full ((2,2),7)
6. random (2,3)
7. arange (0,10,2)

In [ ]:
# list
l = [1,2,3]
lm = l*2
print(lm)

# array
import numpy as np
arr = np.array(l)
arrM = arr*2
print(arrM)

[1, 2, 3, 1, 2, 3]
[3 4 5]


In [ ]:
# comparsion
# array running timing less than list
import numpy as np
import time

# list range(10) -> 0 to 9
start = time.time()
l = [i*500 for i in range(1000000)]
print("list output:",time.time() - start) # 0.06

# array
start = time.time()
arr = np.array(1000000)*500
print("array output:",time.time() - start) # 0.0001


Time taken by list: 0.10216522216796875
Time taken by array: 0.00014090538024902344


In [ ]:
# zeros array 1d
import numpy as np
arr =  np.zeros(5)
print(arr)

# zeros array 2d
arr1 = np.zeros((3,4))
print(arr1)

[0. 0. 0. 0. 0.]
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [ ]:
# ones array 1d
import numpy as np
arr = np.ones(5)
print(arr)
# ones array 2d
arr1 = np.ones((3,4))
print(arr1)

[1. 1. 1. 1. 1.]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [ ]:
import numpy as np
# question zeros -> 2d array -> 10
arr = np.zeros((2,3))+10
print(arr)
# question ones -> 2d array -> 5
arr1 = np.ones((2,3))+5
print(arr1)

[[10. 10. 10.]
 [10. 10. 10.]]
[[6. 6. 6.]
 [6. 6. 6.]]


In [ ]:
# full for 1d
import numpy as np
arr = np.full((3),5)
print(arr)


# full for 2d
import numpy as np
arr1 = np.full((2,3),5)
print(arr1)


# question help of zeros -> 2d -> 6
# question help of full -> 2d -> 1

[0 0 0]
[[5 5 5]
 [5 5 5]]


In [ ]:
#random for 1d 0 -> 1
import numpy as np
arr = np.random.random(5)
print(arr)

# random for 2d 0-> 1
arr1 = np.random.random((2,3))
print(arr1)

[0.52708212 0.18784825 0.44544259 0.7754318  0.9236564 ]
[[0.34794739 0.24080247 0.97403901]
 [0.59373605 0.75061786 0.03581292]]


In [ ]:
#arange for 1d
import numpy as np
arr = np.arange(5)
print(arr)

#arange for 1d || to convert into 2d -> reshape
arr1 = np.arange(0,10,2) # start,stop,step
print(arr1)

[0 1 2 3 4]
[0 2 4 6 8]


**Vector,matrix,tensor**
1. vector (1d)
2. matrix (2d)
3. tensor (3d)

In [ ]:
import numpy as np
# vector 1d list
l = [1,2,3]
print(l)
#vector 1d array
arr = np.array(l)
print(arr)

#matrix 2d list
l = [[1,2,3],[4,5,6]]
print(l)
#matrix 2d array
arr = np.array(l)
print(arr)

#tensor 3d list
l = [[[1,2],[3,4]],[[5,6],[7,8]]]
print(l)
#tensor 3d array
arr = np.array(l)
print(arr)


[1, 2, 3]
[1 2 3]
[[1, 2, 3], [4, 5, 6]]
[[[1, 2], [3, 4]], [[5, 6], [7, 8]]]


**Array properties**
1. shape
2. dimension
3. size
4. dtype

In [ ]:
# array
import numpy as np
arr = np.arange(12) # 1d
# arr = np.arange(12).reshape(3,4) # 3 X 4 => 12  # 2d
print("shape: ",arr.shape)
print("shape: ",np.shape(arr))
print("dimension: ",np.ndim(arr))
print("size: ",np.size(arr))
print("datatype: ",arr.dtype)

shape:  (3, 4)
shape:  (3, 4)
dimension:  2
size:  12
datatype:  int64


**Array Reshaping**
1. reshape()
2. flatten() -> create copy
3. ravel() -> return original
4. transpose

**Numpy Array operations**
1. slicing for 1d,2d,3d


**Looping with numpy**
1. while loop
2. for loop

**Sorting**
1. sort() for 1d
2. sort() for 2d ,use axis=0-> cols,axis=1-> rows


**Filter**
1. array[Expression]
2. array[array>2] || filter with mask

**Fancy indexing vs np.where()**
1. array(list)
2. array([0,1,2])

3. np.where(expression)
4. np.where(array>2)